# BEGIN_KITTY_THEME
# Elemental
include current-theme.conf
# END_KITTY_THEME

background_image /home/kaycee/Pictures/Wallpaper/SpaceAstronaut/LittleAstronaut.png

background_image_layout clamped

background_tint 0.85

background_opacity 0.35
 
font_family Cascadia Code

font_size 13
