# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME

#background_image /home/kaycee/Pictures/Wallpaper/SpaceAstronaut/LittleAstronaut.png
#background_image /home/kaycee/Pictures/Wallpaper/SpaceAstronaut/earth&stars-gruvbox.jpg

#background_image_layout clamped

background_tint 0.75

background_opacity 0.75
 
font_family Cascadia Code

font_size 13.8

hide_window_decorations no

window_padding_width 5

enable_audio_bell no
