## Change the default prefix
# Unbind the default prefix
unbind C-b
# Set new prefix to Ctrl+a
set -g prefix C-a
# Bind Ctrl+a twice to send Ctrl+a to applications
bind C-a send-prefix

## Unbind the default keys first
unbind s
unbind w
# Rebind with swapped functionality
bind s choose-window    # prefix+s now shows window list
bind w choose-session   # prefix+w now shows session list

# Enable Powerline in tmux
set -g status on
set -g status-interval 2
set -g status-justify centre
set -g status-fg white
set -g status-bg black

# Refresh status bar
set -g status-style bg=black,fg=white
set -g status-left "#(bash ~/.config/tmux-powerline/powerline.sh left 2>/dev/null)"
set -g status-right "#(bash ~/.config/tmux-powerline/powerline.sh right 2>/dev/null)"

# Set Powerline theme
set -g status-right-length 50
set -g status-left-length 50

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# enable tmux-resurrect (needed for continuum)
set -g @resurrect-capture-pane-contents 'on'
# enable tmux-continuum continuous saving
set -g @continuum-save-interval '15'   # saves every 15 minutes (default)
# auto-restore last session when tmux starts
set -g @continuum-restore 'on'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'






#  set-option -g status on
#   set-option -g status-interval 2
#   set-option -g status-left-length 60
#   set-option -g status-right-length 90
#   set-option -g status-left "#(~/.config/tmux-powerline/powerline.sh left)"
#   set-option -g status-right "#(~/.config/tmux-powerline/powerline.sh right)"





# Enable mouse scroll
set -g mouse on

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
