[/]
custom-list=['custom0', '__dummy__']

[custom-keybindings/custom0]
binding=['<Super>t']
command='kitty -e tmux'
name='Open Terminal with Tmux'

[media-keys]
terminal=['<Primary><Alt>t', '<Shift><Super>t']
volume-down=['XF86AudioLowerVolume', 'F3']
volume-up=['XF86AudioRaiseVolume', 'F2']

[wm]
close=['<Alt>F4', '<Super>w', '<Primary><Shift>w']
maximize=['<Super>m']
minimize=['<Shift><Super>m']
switch-to-workspace-1=['<Alt>1']
switch-to-workspace-2=['<Alt>2']
switch-to-workspace-3=['<Alt>3']
switch-to-workspace-4=['<Alt>4', '<Alt>4']
switch-to-workspace-5=['<Alt>5']
switch-to-workspace-6=['<Alt>6']
