# Enable Powerline in tmux
set -g status on
set -g status-interval 2
set -g status-justify centre
set -g status-fg white
set -g status-bg black

# Refresh status bar
set -g status-style bg=black,fg=white
set -g status-left "#(bash ~/.tmux/tmux-powerline/powerline.sh left 2>/dev/null)"
set -g status-right "#(bash ~/.tmux/tmux-powerline/powerline.sh right 2>/dev/null)"

# Set Powerline theme
set -g status-right-length 50
set -g status-left-length 50

set -g @plugin 'tmux-plugins/tmux-resurrect'

